name: ci
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Install dependencies backend
              run: pip install -r app/backend/requirements.txt

            - name: Install dependencies frontend
              run: pip install -r app/frontend/requirements.txt

            - name: Test frontend with pytest/selenium
              run: pytest tests/test_frontend.py 

            - name: Test Models with pytest
              run: pytest tests/test_models.py 